// Generated by https://quicktype.io

export interface DiscordUser {
  id:            string;
  username:      string;
  avatar:        string;
  discriminator: string;
  public_flags:  number;
  flags:         number;
  locale:        string;
  mfa_enabled:   boolean;
  email:         string;
  verified:      boolean;
  provider:      string;
  accessToken:   string;
  guilds:        Guild[];
  fetchedAt:     string;
}

export interface Guild {
  id:              string;
  name:            string;
  icon:            null | string;
  owner:           boolean;
  permissions:     number;
  features:        Feature[];
  permissions_new: string;
}

export enum Feature {
  AnimatedIcon = "ANIMATED_ICON",
  Banner = "BANNER",
  Commerce = "COMMERCE",
  Community = "COMMUNITY",
  Discoverable = "DISCOVERABLE",
  EnabledDiscoverableBefore = "ENABLED_DISCOVERABLE_BEFORE",
  InviteSplash = "INVITE_SPLASH",
  MemberVerificationGateEnabled = "MEMBER_VERIFICATION_GATE_ENABLED",
  News = "NEWS",
  Partnered = "PARTNERED",
  PreviewEnabled = "PREVIEW_ENABLED",
  RelayEnabled = "RELAY_ENABLED",
  VanityURL = "VANITY_URL",
  Verified = "VERIFIED",
  VipRegions = "VIP_REGIONS",
  WelcomeScreenEnabled = "WELCOME_SCREEN_ENABLED",
}
